# Generated by Django 5.2 on 2025-08-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Categoria')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Descripción')),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
    ]
