# Generated by Django 5.2.1 on 2025-05-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Comprador'), ('SELLER', 'Vendedor'), ('ADMIN', 'Administrador')], default='CUSTOMER', max_length=15, verbose_name='Rol'),
        ),
    ]
