# Generated by Django 6.0.5 on 2026-07-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_company_address_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje'),
        ),
    ]
