# Generated by Django 5.2 on 2025-08-31 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(unique=True, verbose_name='Contenido')),
            ],
            options={
                'verbose_name': 'Tipo de contenido',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(unique=True, verbose_name='Red Social')),
            ],
            options={
                'verbose_name': 'Red Social',
                'verbose_name_plural': 'Redes Sociales',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('title', models.CharField(verbose_name='Titulo')),
                ('copy', models.TextField()),
                ('cta_text', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('in_design', 'En diseño'), ('scheduled', 'Programado'), ('published', 'Publicado'), ('canceled', 'Cancelado')], default='draft', max_length=20, verbose_name='Estado')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='Programado para')),
                ('content_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='socialmedia.contenttype', verbose_name='Tipo de contenido')),
                ('platform', models.ManyToManyField(to='socialmedia.platform', verbose_name='Redes Sociales')),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
            },
        ),
    ]
