# Generated by Django 6.0.5 on 2026-07-08 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='email_company',
            new_name='email',
        ),
    ]
