# Generated by Django 6.0.7 on 2026-07-31 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['-name'], 'verbose_name': 'Método de pago', 'verbose_name_plural': 'Métodos de pago'},
        ),
    ]
