# Generated by Django 5.2.7 on 2026-05-01 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_invoice_number_alter_invoiceitem_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Pagada')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('method', models.CharField(choices=[('TRANSFER', 'Transferencia'), ('CASH', 'Efectivo'), ('CARD', 'Tarjeta')], default='TRANSFER', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Nº de transferencia o recibo', max_length=100)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.invoice')),
            ],
        ),
    ]
