# Generated by Django 6.0.5 on 2026-07-14 09:07

from django.db import migrations, models


def deduplicate_supplier_names(apps, schema_editor):
    Supplier = apps.get_model('billing', 'Supplier')

    duplicates = (
        Supplier.objects.values('name')
        .annotate(total=models.Count('id'))
        .filter(total__gt=1)
    )

    for row in duplicates:
        name = row['name']
        suppliers = list(Supplier.objects.filter(name=name).order_by('id'))

        for index, supplier in enumerate(suppliers[1:], start=2):
            base_name = f'{name} {index}'
            candidate = base_name
            counter = 2

            while Supplier.objects.filter(name=candidate).exclude(pk=supplier.pk).exists():
                candidate = f'{base_name} {counter}'
                counter += 1

            supplier.name = candidate
            supplier.save(update_fields=['name'])


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_invoiceline_fields'),
    ]

    operations = [
        migrations.RunPython(deduplicate_supplier_names, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Proveedor'),
        ),
    ]
