# Generated by Django 6.0.4 on 2026-05-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_paymentmethods'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentMethods',
            new_name='PaymentMethod',
        ),
    ]
