# Generated by Django 6.0.5 on 2026-07-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_invoice_document_type_document_sequence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-issue_date', '-id'], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
    ]
