# Generated by Django 6.0.4 on 2026-05-04 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_rename_paymentmethods_paymentmethod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['name'], 'verbose_name': 'Metodo de pago', 'verbose_name_plural': 'Metodos de pago'},
        ),
    ]
