# Generated by Django 5.2.7 on 2026-05-06 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_alter_paymentmethod_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
