# Generated by Django 6.0.7 on 2026-07-16 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_paymentmethod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'Métodos de Pago', 'verbose_name_plural': 'Métodos de Pagos'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Suplidor', 'verbose_name_plural': 'Suplidores'},
        ),
    ]
