# Generated by Django 5.2.7 on 2026-05-06 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_remove_invoiceitem_invoice_remove_payment_invoice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['-name'], 'verbose_name': 'Metodo de pago', 'verbose_name_plural': 'Metodos de pago'},
        ),
    ]
