# Generated by Django 5.2.7 on 2026-05-06 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customeruser_city_customeruser_postal_code_and_more'),
        ('billing', '0010_alter_paymentmethod_options'),
        ('company', '0003_alter_company_options_company_postal_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('document_type', models.CharField(choices=[('QUOTE', 'Presupuesto'), ('INVOICE', 'Factura')], default='QUOTE', max_length=10)),
                ('number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='# Factura')),
                ('issue_date', models.DateField(auto_now=True, verbose_name='Fecha de Factura')),
                ('due_date', models.DateField(verbose_name='Fecha de Pago')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ISSUED', 'Emitida/Enviada'), ('ACCEPTED', 'Aceptada'), ('PAID', 'Pagada'), ('CANCELLED', 'Cancelada')], default='DRAFT', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Términos y condiciones o notas para el cliente')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.company', verbose_name='Empresa Emisora')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='invoices', to='accounts.customeruser')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
