# Generated by Django 5.2.7 on 2026-05-06 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_invoice'),
        ('catalogs', '0005_service_contractedservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tax',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.PROTECT, related_name='taxes', to='catalogs.tax'),
            preserve_default=False,
        ),
    ]
