# Generated by Django 6.0.5 on 2026-06-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_alter_invoice_issue_date_invoiceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del producto'),
        ),
    ]
