# Generated by Django 6.0.5 on 2026-06-06 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customer_remove_customeruser_user_alter_user_options_and_more'),
        ('billing', '0018_alter_invoiceitem_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='invoices', to='accounts.customer'),
        ),
    ]
