# Generated by Django 5.2.7 on 2026-05-01 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('PERSON', 'Autónomo / Particular'), ('COMPANY', 'Empresa')], default='PERSON', max_length=20)),
                ('billing_name', models.CharField(max_length=255, verbose_name='Nombre Comercial o Razón Social')),
                ('tax_id', models.CharField(max_length=50, verbose_name='CIF / NIF / NIE')),
                ('address', models.TextField(verbose_name='Dirección de Facturación')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Correo para envío de facturas')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
