# Generated by Django 5.2.7 on 2026-05-06 21:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customeruser_options_alter_customeruser_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Ciudad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customeruser',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='province',
            field=models.CharField(default='Coruña', max_length=200, verbose_name='Provincia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Dirección'),
        ),
    ]
