# Generated by Django 6.0.5 on 2026-06-06 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customeruser_city_customeruser_postal_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('PERSON', 'Autónomo / Particular'), ('COMPANY', 'Empresa')], default='PERSON', max_length=20, verbose_name='Tipo de cliente')),
                ('billing_name', models.CharField(max_length=255, verbose_name='Nombre Comercial o Razón Social')),
                ('tax_id', models.CharField(max_length=50, unique=True, verbose_name='CIF / NIF / NIE')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('province', models.CharField(max_length=100, verbose_name='Provincia')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal')),
                ('country', models.CharField(default='España', max_length=100, verbose_name='País')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Correo de facturación')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['billing_name'],
            },
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='user',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.customer', verbose_name='Cliente'),
        ),
    ]
