# Generated by Django 6.0.5 on 2026-06-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customer_remove_customeruser_user_alter_user_options_and_more'),
        ('billing', '0019_alter_invoice_customer'),
        ('catalogs', '0007_delete_contractedservice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerUser',
        ),
    ]
