# Generated by Django 5.2.7 on 2026-05-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Empresa')),
                ('email_company', models.EmailField(max_length=200, verbose_name='Email')),
                ('phone', models.CharField(max_length=200, verbose_name='Teléfono')),
                ('address', models.CharField(max_length=200, verbose_name='Dirección')),
                ('website', models.URLField(blank=True, null=True)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo', verbose_name='Logo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
