# Generated by Django 5.2.7 on 2026-05-02 04:35

import apps.company.models
import django.contrib.staticfiles.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=django.contrib.staticfiles.storage.StaticFilesStorage(), upload_to=apps.company.models.force_logo_name, verbose_name='Logo Principal (Sobrescribe static/img/logo.png)'),
        ),
    ]
