# Generated by Django 5.2.7 on 2025-11-07 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name': 'Impuesto', 'verbose_name_plural': 'Impuestos'},
        ),
    ]
