# Generated by Django 5.2.7 on 2026-05-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_rename_rate_tax_percentage_remove_product_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
