# Generated by Django 5.2.7 on 2026-05-01 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customeruser_options_alter_customeruser_phone_and_more'),
        ('catalogs', '0004_alter_product_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Servicio')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Base')),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=21, max_digits=5, verbose_name='IVA %')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activo?')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='ContractedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cuota Mensual')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('PENDING', 'Pendiente'), ('EXPIRED', 'Vencido'), ('CANCELLED', 'Cancelado')], default='ACTIVE', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracted_services', to='accounts.customeruser')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='catalogs.service')),
            ],
            options={
                'verbose_name': 'Servicio Contratado',
                'verbose_name_plural': 'Servicios Contratados',
            },
        ),
    ]
