# Generated by Django 6.0.5 on 2026-06-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0006_rename_active_category_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContractedService',
        ),
    ]
