# Generated by Django 6.0.5 on 2026-07-08 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0006_rename_active_category_is_active_and_more'),
        ('core', '0002_alter_company_address_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.tax'),
        ),
        migrations.DeleteModel(
            name='ContractedService',
        ),
        migrations.DeleteModel(
            name='Tax',
        ),
    ]
