# Generated by Django 6.0.7 on 2026-07-31 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0007_delete_contractedservice'),
        ('catalogs', '0007_remove_tax_created_by_remove_tax_updated_by_and_more'),
    ]

    operations = [
    ]
