# Generated by Django 6.0.4 on 2026-05-04 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('url', models.URLField()),
                ('page_type', models.CharField(choices=[('home', 'Home Page'), ('services', 'Services Page'), ('blog', 'Blogs Post'), ('landing', 'Landing PAge'), ('contact', 'Contact Page'), ('other', 'Other')], default='other', max_length=20)),
                ('label', models.CharField(help_text='Nombre interno, identificación de pagina', max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Notas del administrador', null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='seo.seoproject')),
            ],
            options={
                'verbose_name': 'SEO Url',
                'verbose_name_plural': 'SEO Urls',
                'ordering': ['project', 'url'],
                'unique_together': {('project', 'url')},
            },
        ),
    ]
