# Generated by Django 6.0.4 on 2026-05-06 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_seourl'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'Corriendo'), ('completed', 'Completado'), ('failed', 'Errores')], default='pending', max_length=20)),
                ('seo_score', models.PositiveIntegerField(default=0, help_text='Puntuación SEO general del 0 al 100')),
                ('status_code', models.PositiveIntegerField(default=0, help_text='Código HTTP')),
                ('title', models.TextField(blank=True)),
                ('title_length', models.PositiveIntegerField(default=0)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_description_length', models.PositiveIntegerField(default=0)),
                ('h1', models.TextField(blank=True, null=True)),
                ('h1_count', models.PositiveIntegerField(default=0)),
                ('h1_length', models.PositiveIntegerField(default=0)),
                ('images_total', models.PositiveIntegerField(default=0)),
                ('images_without_alt', models.PositiveIntegerField(default=0)),
                ('internal_links', models.TextField(blank=True, null=True)),
                ('external_links', models.TextField(blank=True, null=True)),
                ('canonical', models.URLField(blank=True, null=True)),
                ('has_sitemap', models.BooleanField(default=False)),
                ('has_robots_txt', models.BooleanField(default=False)),
                ('has_schema', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('seo_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='seo.seourl')),
            ],
            options={
                'verbose_name': 'SEO Auditoria',
                'verbose_name_plural': 'SEO Auditorias',
                'ordering': ['-created_at'],
            },
        ),
    ]
