# Generated by Django 6.0.4 on 2026-05-06 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_seoaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiSeoRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('summary', models.TextField(help_text='Resumen general del análisis SEO.')),
                ('priority_actions', models.JSONField(blank=True, default=list, help_text='Lista de acciones prioritarias.')),
                ('strengths', models.JSONField(blank=True, default=list, help_text='Aspectos positivos detectados.')),
                ('weaknesses', models.JSONField(blank=True, default=list, help_text='Debilidades detectadas.')),
                ('client_explanation', models.TextField(blank=True, help_text='Explicación simplificada para el cliente.')),
                ('admin_notes', models.TextField(blank=True, help_text='Notas técnicas internas visibles solo para administradores.')),
                ('estimated_impact', models.CharField(blank=True, help_text='Impacto esperado de las mejoras.', max_length=100)),
                ('estimated_difficulty', models.CharField(blank=True, help_text='Nivel de dificultad de implementación.', max_length=100)),
                ('visible_to_client', models.BooleanField(default=True)),
                ('audit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendation', to='seo.seoaudit')),
            ],
            options={
                'verbose_name': 'AI SEO Recommendation',
                'verbose_name_plural': 'AI SEO Recommendations',
            },
        ),
        migrations.CreateModel(
            name='PageSpeedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('mobile_score', models.PositiveIntegerField(blank=True, help_text='Puntuación de rendimiento móvil de 0 a 100.', null=True)),
                ('desktop_score', models.PositiveIntegerField(blank=True, help_text='Puntuación de rendimiento escritorio de 0 a 100.', null=True)),
                ('lcp', models.FloatField(blank=True, help_text='Largest Contentful Paint en segundos.', null=True)),
                ('inp', models.FloatField(blank=True, help_text='Interaction to Next Paint en milisegundos.', null=True)),
                ('cls', models.FloatField(blank=True, help_text='Cumulative Layout Shift.', null=True)),
                ('fcp', models.FloatField(blank=True, help_text='First Contentful Paint en segundos.', null=True)),
                ('ttfb', models.FloatField(blank=True, help_text='Time To First Byte en segundos.', null=True)),
                ('speed_index', models.FloatField(blank=True, help_text='Speed Index en segundos.', null=True)),
                ('total_blocking_time', models.FloatField(blank=True, help_text='Total Blocking Time en milisegundos.', null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Respuesta completa o parcial de PageSpeed API.')),
                ('audit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagespeed', to='seo.seoaudit')),
            ],
            options={
                'verbose_name': 'PageSpeed Result',
                'verbose_name_plural': 'PageSpeed Results',
            },
        ),
        migrations.CreateModel(
            name='SeoIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('technical', 'Technical SEO'), ('content', 'Content'), ('performance', 'Performance'), ('accessibility', 'Accessibility'), ('indexing', 'Indexing'), ('links', 'Links'), ('schema', 'Schema'), ('other', 'Other')], default='other', max_length=50)),
                ('issue_type', models.CharField(help_text='Tipo interno del problema. Ej: missing_meta_description.', max_length=100)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('opportunity', 'Opportunity')], max_length=20)),
                ('title', models.CharField(help_text='Título corto del problema.', max_length=255)),
                ('description', models.TextField(help_text='Explicación del problema detectado.')),
                ('recommendation', models.TextField(blank=True, help_text='Qué se recomienda hacer para solucionarlo.')),
                ('is_fixed', models.BooleanField(default=False, help_text='Marca si el problema ya fue solucionado.')),
                ('fixed_at', models.DateTimeField(blank=True, null=True)),
                ('visible_to_client', models.BooleanField(default=True, help_text='Controla si este problema se muestra al cliente.')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='seo.seoaudit')),
            ],
            options={
                'verbose_name': 'SEO Issue',
                'verbose_name_plural': 'SEO Issues',
                'ordering': ['severity', '-created_at'],
            },
        ),
    ]
