# Generated by Django 6.0.4 on 2026-05-06 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0004_aiseorecommendation_pagespeedresult_seoissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Explicación de la mejora realizada o planificada.')),
                ('category', models.CharField(choices=[('technical', 'Technical SEO'), ('content', 'Content'), ('performance', 'Performance'), ('accessibility', 'Accessibility'), ('indexing', 'Indexing'), ('links', 'Links'), ('schema', 'Schema'), ('other', 'Other')], default='other', max_length=50)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=30)),
                ('before_value', models.TextField(blank=True, help_text='Estado antes de la optimización.')),
                ('after_value', models.TextField(blank=True, help_text='Estado después de la optimización.')),
                ('result_summary', models.TextField(blank=True, help_text='Resumen del resultado obtenido.')),
                ('visible_to_client', models.BooleanField(default=True, help_text='Controla si esta optimización se muestra en el panel cliente.')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimizations', to='seo.seoproject')),
                ('related_issue', models.ForeignKey(blank=True, help_text='Problema SEO que esta optimización intenta solucionar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optimizations', to='seo.seoissue')),
                ('seo_url', models.ForeignKey(blank=True, help_text='URL específica relacionada con esta optimización, si aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optimizations', to='seo.seourl')),
            ],
            options={
                'verbose_name': 'SEO Optimization',
                'verbose_name_plural': 'SEO Optimizations',
                'ordering': ['-created_at'],
            },
        ),
    ]
